### ISSUE TITLE
Python 3.11: mutable default PhoneNumber for field source is not allowed

### ISSUE THREAD

**Issue by oberstetpanamax** [niksabaldun/aiosmpplib#1]
On CPython 3.11, I am running into:

```
(cpy3113_1) oberstet@thinkpad-t430s:~$ python -V
Python 3.11.3
(cpy3113_1) oberstet@thinkpad-t430s:~$ pip show aiosmpplib
Name: aiosmpplib
Version: 0.6.3
Summary: Python asyncio SMPP client library.
Home-page: https://github.com/niksabaldun/aiosmpplib
Author: Nikša Baldun
Author-email: niksa.baldun@gmail.com
License: MIT
Location: /home/oberstet/cpy3113_1/lib/python3.11/site-packages
Requires: 
Required-by: jasmin-nga
(cpy3113_1) oberstet@thinkpad-t430s:~$ python -c "from aiosmpplib import PhoneNumber"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/oberstet/cpy3113_1/lib/python3.11/site-packages/aiosmpplib/__init__.py", line 2, in <module>
    from .esme import ESME
  File "/home/oberstet/cpy3113_1/lib/python3.11/site-packages/aiosmpplib/esme.py", line 8, in <module>
    from .broker import AbstractBroker, SimpleBroker
  File "/home/oberstet/cpy3113_1/lib/python3.11/site-packages/aiosmpplib/broker.py", line 5, in <module>
    from .protocol import SmppMessage
  File "/home/oberstet/cpy3113_1/lib/python3.11/site-packages/aiosmpplib/protocol.py", line 131, in <module>
    @dataclass
     ^^^^^^^^^
  File "/home/oberstet/cpy3113/lib/python3.11/dataclasses.py", line 1223, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/home/oberstet/cpy3113/lib/python3.11/dataclasses.py", line 1213, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oberstet/cpy3113/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oberstet/cpy3113/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'aiosmpplib.state.PhoneNumber'> for field source is not allowed: use default_factory
(cpy3113_1) oberstet@thinkpad-t430s:~$ 
```

https://github.com/niksabaldun/aiosmpplib/blob/b142b784a47df822f7290352c0381b0dfb9d559f/aiosmpplib/protocol.py#L131

----------

This does not happen on older Python, e.g. here is the same test on PyPy:

```
(pypy39_1) oberstet@thinkpad-t430s:~$ python -V
Python 3.9.16 (feeb267ead3e6771d3f2f49b83e1894839f64fb7, Dec 29 2022, 14:23:21)
[PyPy 7.3.11 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)]
(pypy39_1) oberstet@thinkpad-t430s:~$ pip show aiosmpplib
Name: aiosmpplib
Version: 0.6.3
Summary: Python asyncio SMPP client library.
Home-page: https://github.com/niksabaldun/aiosmpplib
Author: Nikša Baldun
Author-email: niksa.baldun@gmail.com
License: MIT
Location: /home/oberstet/pypy39_1/lib/pypy3.9/site-packages
Requires: 
Required-by: jasmin-nga
(pypy39_1) oberstet@thinkpad-t430s:~$ python -c "from aiosmpplib import PhoneNumber"
(pypy39_1) oberstet@thinkpad-t430s:~$ 
```

**Comment by oberstetpanamax** [comment]
fixed in https://github.com/niksabaldun/aiosmpplib/pull/2
